# \u7AEF\u53E3\u53F7
server:
  port: 9004


# \u65E5\u5FD7\u683C\u5F0F
logging:
  pattern:
    console: '%d{HH:mm:ss.SSS} %clr(%-5level) ---  [%-15thread] %cyan(%-50logger{50}):%msg%n'


# \u914D\u7F6EMybatis-plus
mybatis-plus:
  global-config:
    db-config:
      # \u8868\u540D\u524D\u7F00
      table-prefix: bz_
      # \u4E3B\u952E\u751F\u6210\u7B56\u7565\u4E3A\u81EA\u589E
      id-type: auto
  configuration:
    # \u5173\u95ED\u5217\u540D\u81EA\u52A8\u9A7C\u5CF0\u547D\u540D\u6620\u5C04\u89C4\u5219
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # \u5F00\u542Fsql\u65E5\u5FD7


spring:
  # \u6570\u636E\u6E90
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///baizhanshopping?serverTimezone=UTC
    username: root
    password: root@1234


dubbo:
  application:
    name: shopping_category_service # \u9879\u76EE\u540D
  registry:
    address: zookeeper://192.168.66.100 # \u6CE8\u518C\u4E2D\u5FC3\u5730\u5740
    port: 2181 # \u6CE8\u518C\u4E2D\u5FC3\u7AEF\u53E3\u53F7
    timeout: 10000 # \u6CE8\u518C\u5230zk\u4E0A\u8D85\u5E02\u65F6\u95F4,ms
  protocol:
    name: dubbo # dubbo\u4F7F\u7528\u7684\u534F\u8BAE
    port: -1 # \u81EA\u52A8\u5206\u914D\u7AEF\u53E3
  scan:
    base-packages: com.yunshucloud.shopping_category_service.service # \u5305\u626B\u63CF
